### ISSUE TITLE
Javascript assignment | 19march 3pm

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#102]
Functions
Parameterized function
Arrow function 
Alert hello on Button click event
Input name in text and alert on submit of form
Input 2 numbers from textbox and on  submit display result inside a div.

**Comment by Ansu-s** [comment]
- I have added the javascript assignment code and screenshots [here](https://github.com/Ansu-s/active-tasks/tree/main/js-tasks/functions-events) please check it
