### ISSUE TITLE
design a calculator using js and es6 concepts | 21st March 3pm

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#104]
Use html, css, js, es6 only.
Do operations like add, sub, multi, division with 2 natural numbers 
Attach screenshots.
dont use any framework

**Comment by Ansu-s** [comment]
Uploaded the calculator only using html, css and javascript [here](https://github.com/Ansu-s/active-tasks/tree/main/js-tasks/calculator-html-css-js)

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/calculator
