### ISSUE TITLE
dynamic html css table using js | 22nd March 3pm

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#105]
Add Row Button should add a row to existing table.
Delete button should delete the selected rows of table.
Add screesnshots.
Dont use any frameworks. pure html, css, js.

**Comment by Ansu-s** [comment]
I have created a table where we can add or delete rows accroding to our need and I have added the explanation about the working of the table as well[here](https://github.com/Ansu-s/active-tasks/tree/main/js-tasks/dynamic-tables)

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/javascript/tree/master/dynamic-Table
