### ISSUE TITLE
read write to table and delete from table using html css js | 23rd March 3pm

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#106]
Read an input say city name from textbox. On submit add the city to existing city table.
Display the list of cities in a html table.
Delete the selected cities from the table.

**Comment by Ansu-s** [comment]
I have created a page where we can take input form the user and add it to an existing table, we can perform delete operation on multiple rows as well. I have added the code [here](https://github.com/Ansu-s/active-tasks/tree/main/js-tasks/read-write-table)

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/javascript/compare/master?expand=1
