### ISSUE TITLE
javascript assignment | 1st April

### ISSUE THREAD

**Issue by Subhransupanda2000** [learning-project-01/bookstore-app#108]
* Higher Order Functions,  Callback hell , async and promise, fetch method to show records in a table.
(Submit with screenshot on 1st April)

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/javascript/pulls

**Comment by Ansu-s** [comment]
I have added the code [here](https://github.com/Ansu-s/active-tasks/tree/main/js-tasks/functions-promises-async), working to properly implement the fetch method will update soon

**Comment by rkpatra201** [comment]
> https://github.com/Subhransupanda2000/javascript/pulls

It is missing fetch example
