### ISSUE TITLE
Http Session Management with servlet application 

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#21]
Understand session, cookies, headers with examples.

Why http is stateless.

This example is not based on spring boot app.

Create a maven based servlet project to demonstrate session, cookies, headers.
Push code to your repo and share link below.

Add a Readme file to explain the concept.

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/tomcat-server

**Comment by Ansu-s** [comment]
Updated the readme file with required content.

**Comment by rkpatra201** [comment]
> Updated the readme file with required content.

Fantastic.  But let me know if you have any doubts on Readme file notes you added.
