### ISSUE TITLE
add unit test case for controllers and service using mockito

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#23]
code coverage should be 90%

**Comment by Ansu-s** [comment]
I am learning the mockito framework so their is this error occuring in the project when I am trying to run the tests. Please review the code and provide feedback I haven't finished all the test cases, I wrote a single one for demo only. Uploaded the code to a new brach [task/test](https://github.com/Ansu-s/bookstore-app/tree/task/tests) .

I have uploaed the problem I am facing in [error.md](https://github.com/Ansu-s/bookstore-app/blob/task/tests/error.md).

**Comment by rkpatra201** [comment]
> I am learning the mockito framework so their is this error occuring in the project when I am trying to run the tests. Please review the code and provide feedback I haven't finished all the test cases, I wrote a single one for demo only. Uploaded the code to a new brach [task/test](https://github.com/Ansu-s/bookstore-app/tree/task/tests) .
> 
> I have uploaed the problem I am facing in [error.md](https://github.com/Ansu-s/bookstore-app/blob/task/tests/error.md).

I don't see where is error.md

**Comment by Ansu-s** [comment]
Added tests for controllers to the branch task/tests 
![Screenshot 2024-02-07 012029](https://github.com/learning-project-01/bookstore-app/assets/130679461/52aa6d2e-c0b6-4fad-8efc-73e0ac82241c)
