### ISSUE TITLE
understand database transaction

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#24]
what is ACID in database transaction.

**Comment by Ansu-s** [comment]
https://github.com/Ansu-s/active-tasks/tree/main/database-concepts/acid-properties

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/SQL/blob/main/ACID-PROPERTIES/README.md

**Comment by rkpatra201** [comment]
> https://github.com/Subhransupanda2000/SQL/blob/main/ACID-PROPERTIES/README.md

This is not explaining acid properties
