### ISSUE TITLE
servlet filter , listener,, and servlet example

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#26]

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/servlet/tree/master

**Comment by Ansu-s** [comment]
please check the error.md , I am facing some errors and could't figure out them  

https://github.com/Ansu-s/test-projects/blob/master/error.md

**Comment by rkpatra201** [comment]
> please check the error.md , I am facing some errors and could't figure out them  
> 
> https://github.com/Ansu-s/test-projects/blob/master/error.md

What is your current configuration given. I have shared one servlet example earlier. You also did one assignment with session example

**Comment by Ansu-s** [comment]
I have followed your solution and implemented here 

https://github.com/Ansu-s/active-tasks/tree/main/servlet-features
