### ISSUE TITLE
Implement lru cache 

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#32]
- Why lru cache
- Where it is used
-Implementation using java code
- Write junit test to show the Implementation is working.
- use good naming convention and formatting.

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/JAVA/pull/10

**Comment by Subhransupanda2000** [comment]
@rkpatra201  https://github.com/Subhransupanda2000/JAVA/blob/master/LRU-CACHE/README.md

**Comment by Ansu-s** [comment]
https://github.com/Ansu-s/active-tasks/tree/main/java-challenges/lrucache
