### ISSUE TITLE
design document for checkout api of cart

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#33]
- this task is not coding but to make a document about the changes for the implementation to be done later
- on checkout we should give response of cart items whose status is buy_now.
- list down the approach required to achieve the task
- list down the changes required in which files for this task.

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/JAVA/blob/master/checkout/README.md

**Comment by Subhransupanda2000** [comment]
https://github.com/learning-project-01/cab-booking-app/blob/main/8points/README.md
