### ISSUE TITLE
cart summary api is giving wrong response

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#36]
![image](https://github.com/learning-project-01/bookstore-app/assets/17001948/fc6b3558-ad67-420a-8b0b-c46503b65f12)

User has added 18 units of Product A. 
Unit price for Product A is 20. 
So total should be 18 * 20 = 360 but it shows 400 (see line 12 of image attached above )which is wrong.

**Comment by Ansu-s** [comment]
Changed the code and tested it and it is running correctly  

![Screenshot (261)](https://github.com/learning-project-01/bookstore-app/assets/130679461/b81252e3-1731-4aad-a429-2d9bbe2f857a)

**Comment by rkpatra201** [comment]
@Ansu-s  / @Subhransupanda2000 any one of them please create PR for this. I have to merge this defect today. We cant take it delayed though it is a learning project we should show some interest else better we stop here.
