### ISSUE TITLE
understand redis and java integration | Feb 7

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#42]
submit on 7th Feb 3pm without fail

- what is redis
- why it is used
- what is redis architecture 
- pros and cons of redis
- setup redis in local 
- integrate java with redis. how can we use map and queue data structure of redis in java.

**Comment by Ansu-s** [comment]
I haven't been able to implement in a spring boot application for now 
https://github.com/Ansu-s/active-tasks/tree/main/java-redis

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/Redis
