### ISSUE TITLE
spring boot filter integration | Feb 8

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#53]
Submit: Feb 8, 2024 | 3pm
Reference: https://www.baeldung.com/spring-boot-add-filter
What is a filter?
Why filter is used?
Using logger print the request url and headers inside filter.

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/springboot-filter-integration
Im having issue with this application not able to run . I have mentioned the error in my issue section

**Comment by Ansu-s** [comment]
https://github.com/Ansu-s/active-tasks/tree/main/spring-filter
