### ISSUE TITLE
contract of equals and hashcode | Feb 9

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#57]
````text
I have employee class as below:

class Employee{
 private Integer id;
 
 public Employee(int id){
   this.id = id;
 }
 
 // set 
 // get

}

I am trying to put the employee objects in a hashset like below.

Set<Employee> set = new HashSet();
set.add(new Employee(100));
set.add(new Employee(101));
set.add(new Employee(100));

I want at  the end size of set should be 2.

Someone suggested use equals() method override in Employee class.
Someone suggested use hashCode() method override in Employee class.
Someone suggested use both equals() and hashCode() method override in Employee class. 

I am confused which one I should follow.
What can be the contract between hashCode and equals?

What is the internal data structure used in hashset?
What is the internal data structure used in linked hashset?
What is the internal data structure used in treeset?

Can you guys help me here?
````

**Comment by Ansu-s** [comment]
[Internal workings](https://github.com/Ansu-s/active-tasks/tree/main/java-concepts)  This file contains all the internal workings of the above mentioned structures. 
[Hashset/Hashmap internal working](https://github.com/Ansu-s/active-tasks/blob/636a3cfd9f5bd67f8518af0f0f299b5ed679b5f8/java-collections/HashSet%26HashMap.md?plain=1#L3) This is some related reference to the topic. 
I am unable to understand this statement - **I want at  the end size of set should be 2**

**Comment by rkpatra201** [comment]
> [Internal workings](https://github.com/Ansu-s/active-tasks/tree/main/java-concepts)  This file contains all the internal workings of the above mentioned structures. 
> [Hashset/Hashmap internal working](https://github.com/Ansu-s/active-tasks/blob/636a3cfd9f5bd67f8518af0f0f299b5ed679b5f8/java-collections/HashSet%26HashMap.md?plain=1#L3) This is some related reference to the topic. 
> I am unable to understand this statement - **I want at  the end size of set should be 2**
> 

Can you help me ro solve above code?

**Comment by rkpatra201** [comment]
> Set<Employee> set = new HashSet();
> set.add(new Employee(100));
> set.add(new Employee(101));
> set.add(new Employee(100));

Here employee id 100 is duplicate. So I want even if I add above 3 elements but the size of set should be 2 because the unique id of employee are 100 , 101.

cc @Ansu-s

**Comment by Subhransupanda2000** [comment]
You have a Employee set with 3 values 100,101,100. Now we want the size of set 2. We know duplicate values are not allowed here. we should override both equal and hashcode method. 
* Equal method compare location of two objects and hashcode compare the vale of two object.
* So in this case  equal method compare the id. and then hashcode method will compare the hash value if we will get true then the output will be 2.
* https://github.com/Subhransupanda2000/JAVA/blob/master/collection/internalwork/README.md

**Comment by rkpatra201** [comment]
> You have a Employee set with 3 values 100,101,100. Now we want the size of set 2. We know duplicate values are not allowed here. we should override both equal and hashcode method. 
> * Equal method compare location of two objects and hashcode compare the vale of two object.
> * So in this case  equal method compare the id. and then hashcode method will compare the hash value if we will get true then the output will be 2.
> * https://github.com/Subhransupanda2000/JAVA/blob/master/collection/internalwork/README.md

Can you update what should be the Employer class changes required as per your suggestion @Subhransupanda2000

**Comment by Ansu-s** [comment]
- If two objects are same accoring to the equals() ,then they must have same hashcode() as equals checks for reference quality (as if both the references are pointing to the same object in memory)
- If we use hashcode() to check their hash, then two objects can have same hash value but may not be same according to equals() , this problem is known as hash code collision.

- If we only override equals() only then the hascode() will see each element as unique even if they have same id.
- For our case if we only use hashCode() method override in Employee class then it will relay on default equals() which is quality reference so duplicates may be present.
- We shoud override both equals() and hashcode() to avoid duplicates here.

**Comment by Subhransupanda2000** [comment]
```
class Employee {
    private Integer id;
    public Employee(int id) {
        this.id = id;
    }
    public Integer getId() {
        return id;
    }
    @Override
    public boolean equals(Object o) {
       Employee employee = (Employee) o;
        return Objects.equals(id, employee.id);
    }
 @Override
    public int hashCode() {
        return Objects.hash(id);
    }
  public static void main(String[] args) {
        Set<Employee> set = new HashSet();
        set.add(new Employee(100));
        set.add(new Employee(101));
        set.add(new Employee(100));
        System.out.println("Size of set: " + set.size());
    }
}
```

**Comment by rkpatra201** [comment]
Perfect
