### ISSUE TITLE
Design document for place order

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#64]
As of now when we do checkout it shows us buy now items.

We want to do place order. With place order
- user should able to link existing address for order
- use should specify the existing address is of type home or office for the order.
- we should prepare a order summary for the order.
- after successful order placed the units should be reduced in catalog for the items

@Subhransupanda2000 @Ansu-s both together can work on this. 

Once you guys are ready, show me the document for review.

**Comment by Ansu-s** [comment]
@Subhransupanda2000  and @Ansu-s  we worked on this and created this basic document show caseing how the initialization of the feature should be done  
https://github.com/Ansu-s/active-tasks/blob/main/java-tasks/order-design.md
