### ISSUE TITLE
Line by line explaining code flow

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#65]
- Use a Readme.md file to answer this.
- Start from controller method.
- You should write line of code. Just below comment what it does.
- Explain about each method parameters and return type you found in the flow.

Add Item flow by @Ansu-s 
Cart summary by @Subhransupanda2000

**Comment by Ansu-s** [comment]
https://github.com/Ansu-s/active-tasks/blob/main/java-tasks/codeflow.md

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/bookstore-application/blob/master/workflow/README.md
