### ISSUE TITLE
document and demo only code | Feb 15 | Feb 16

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#69]
Document and Demo should cover the PR changes: https://github.com/learning-project-01/bookstore-app/pull/67

@Subhransupanda2000 Your demo is Feb 15.
@Ansu-s Your demo is Feb 16

**Comment by Ansu-s** [comment]
https://github.com/Ansu-s/active-tasks/blob/main/java-tasks/auth-process.md

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/bookstore-application/blob/master/login-auth/README.md
