### ISSUE TITLE
design uml diagrams using appdiagrams.net | Feb 25

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#77]
Below UML is required for project documentation. If you don't need documentation, you comment as it is not required before Feb 20th, so that I will give next assignment.

draw.io is same as appdiagrams.net

## UML

https://creately.com/blog/diagrams/uml-diagram-types-examples/

https://www.youtube.com/watch?v=ncfg1WEwdkw&list=PLUny-2f3VZwIDEj4JFW9v1Bm0Td2kWwHN (prepare draw io for this and share with me)

https://www.youtube.com/watch?v=WnMQ8HlmeXc

## Practical:

https://www.startertutorials.com/uml/uml-diagrams-library-management-system.html (practice and share)

https://www.gyaanibuddy.com/assignments/assignment-detail/uml-diagrams-for-ecommerce/ (practice and share)

## Learn:

https://www.youtube.com/watch?v=rsTWufuP328

https://www.guru99.com/uml-relationships-with-example.html

**Comment by Ansu-s** [comment]
UML diagrams for boostore-app 
- [Class diagram](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&page-id=l_DYEExG9BvdglwbmccF&title=class%20diagram%202.drawio#R%3Cmxfile%3E%3Cdiagram%20id%3D%22F6dWzTtE6Bx4wvTb5q8D%22%20name%3D%22Page-1%22%3E7Vxdd6M2EP01fnQO39iPsZPs7jlpd0%2FTbrf7JoOC1QCiIK%2Ft%2FPpKRsKAZINjME67eWjRgISYuTNzNZJ3ZM6jzYcUJMtfsA%2FDkaH5m5F5NzIMU7M1%2Bj8m2eYS3XDsXBKkyOeyveAJvUIu5B2DFfJhVnmQYBwSlFSFHo5j6JGKDKQpXlcfe8Zh9a0JCKAkePJAKEv%2FRD5Z5tKJ%2BC4m%2FwhRsBRv1jV%2BZwG8lyDFq5i%2FL8YxzO9EQAzDH82WwMfrksi8H5nzFGOSX0WbOQyZXoXG8n4PB%2B4WU05hTFp18HTfmlqerk8czfT9MR%2FhBwhXXA0zjF8yglM4BknCZ022QknZGkUhoN9nzpYkCqlQp5feEoX%2BI9jiFZtFRqhCRGtGWynh1qazM2c7TUE2IdYqNMIaHo6Qx69DsIDhrFDtHIc4pbd2ymWjpvilsBObwzOOyQOIUMjw9xWmPogBF%2FO361TdMxCiIKYNj2oM0gFnsgqFTmBK4KYk4ir9AHEESbqlj%2FC7Frfuttpc71HkChQtSwiaTrmDAI7coBh5b0J6wa3Y0qKGZNGWRpQMpdDMIfg0q4rrxpB1Y01VunE70E2sO9ls%2Fmo8Le4Nc%2FN1%2B5thfR8brqQgL4WAUJfVcOpTTNTVRT%2BNVFUlgYgpANFQcstvRMj3WfdZCjP0Cha7oZhOE4xisvskezay79hYK4IzDtAC2DW0P6MwrIlaGMdobRxx16gC2bZla6mMZWo92cqUsQt9GrR5E6dkiQMcg%2FB%2BL63Fl%2F0zjxgnXMl%2FQ0K2HOpM%2F1XrUo2m22%2Bs%2F40tmn%2Fx4XaNu02lteWt9ibJ8Cr14DGQTngCBGkAyTENcQ9kajlq4hSGgKAf1VzXvXNNJOd6RPHLLvOhJEFxwN7q%2B9QtMsm06yUi8CkBO82sKcuomqUPxNtVwDu6DPgizXeNeGn2ln0U7dzxq%2FAu6acpYdLofstoUk32gNgM81xcygA58n3RwwtBliHv9yWK8xu8W%2B4vfqmTwreUPvjGDN4aBGXXcTTb1YGhTeh%2FNdfUx3bXXsO7fmHhvRRQtSq%2BChoghsgDAe9Vg04xjVZoOvSJR3nAEiTsMtoEjNPfLJIovuHCMrJEdntkCPtCsxVBmGW5BSYER4ehNzLM592fIkMSBoRZAlNEP5Ll0Dv6PZTqwy970YwyyBAxqN5BRq5n2TZaYDYrejtCMUvarflkr4zx7EA0qQFlquBJijhk9ZZ55YXB55wcaUlII7R%2FDdHbMW7sqtpMFfWW1WZ0oLb1h0%2Fmb580LXh6eE2%2BJytt%2Fe2z4MMX5isbRHK6Yti8WdAVer1nK6xxHlmRnjHlYHtonMtTlEOzLYH6E4GRzES6WyCdjOk6JRlbEqINV7lg6isUTIfFtFvGtH4upk0Z01LmNC9EDiZ6xdKmWVvy5k7VBTlQ2lU%2FTjcvG6z%2BU4bV3IphLac3wx76xGOsryFR91WeK5UwKC%2FUdn9nkLAUE8Bp6GkIaR%2BKXa1GLwxRsCsvDy1XDsZ6X7FYt4b12fYuWy6i6M4pZZRdq7QKOCMCqHWo4CzqB91LJQLKY6elv2paqFdC%2B04Lcgj5iuCaSjxAQIiDUwNKH66pW07NN4vsWab%2Bxfqga%2FKvLn7Ja6YhvLVLV3FauorQ6ZWUIcW8VRhOyTUA2KnjtyAJJfxOFDy%2FN%2FTqk0FSi0gTeiVF7Avvb6%2B1twa52zYfONcFcnkj69b32YfgKwK6IlJPFJH6kkgfJixfAdKFRpuRfqmVklPlOnZ9X6VnrmOYgyBB0Olysa6g1s10%2BhQyPQR6DOsy6LFq4LkwURb6OEb30iWOFis6n9kAoXfi3rjV0Gvrcug1XRVJ7m1LX4CjpLX5Enov7LDQFaQr4wCmBstV8jYeK1mzbvFOWdh7kfT2Xg%2BsnE4uaudVNNlaFz2vMiyF1m6cCrcY01yhWf1WW47usl%2BIRZhm1WmNlvVWeSCtNlDdrbvbrldvusqll18x%2BenrfCFhXZezm87A3m5NpzV31zWnJ3cX1KaRJFptSeKk6%2BBwnjHlxfTIcELmWgt6EZCdmnIB25ugjz4DrgnnnxU7vz37CMMfkHnaXiS68rMTeX86wXyI6rBUXHqV2s2VDig5vMIjFad5pHCgoltVvLYHSnu%2Fnjbud6vOTvdzAE%2FCwB%2BZ4jzwgKcDxrpeP%2FMiR0Glwjo5HyB%2FgHt2DPzfnWB8%2B2L%2BLftwLVAo9hSPbZ23DeudH0dud7BSr%2B%2B4HqB8FAxgW3qMM57D7zFs5XsOMciG5%2BlFPoPO9vvlkCU7ZH6usrkG8U52%2Ftsj%2BpSFZG03Zujjl8Ps8%2FdXolbEGPnHRG035jvfl39z%2FlNslmcUriv5h3NV4zR44uA%2FigOpJxLiaQY%2BweWk07uGJnudqtjWX21yCKd7m%2FMMmXyNWvIt2hcqvA%2ByafP%2BzGQ7g1qpxWGYLndH3pDyD1DIhpVn%2FSc8nUUfmcrFuyMrK9Ua9CrLfqefyTzdanaz1S6aM%2BSTRnT5lZH8l47vx3T9eFijqS5asJVLfI84YKX1n1StYVP0QL4fyufEsktRrF3qB6q1e%2FuK2iy7Mc5d5ZY%2BoE%2BSTd6tVruV6sB5UVC79WhyRoTp6Q6BIAWRupLbVPQtT7mrqi9dZz88TLT5vM%2FS76kwMsVxGxEQNEcGkqF1cxqBNvf%2FrErOafb%2Fbo15%2Fy8%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22l_DYEExG9BvdglwbmccF%22%20name%3D%22Page-2%22%3E7V1tc6M4Ev41rprdKrt4t%2F0xdpLbqc3cZJO52t2PCsi2LoC8ICf2%2FvprgWReBAbH4JmtI5WaMe3WC1L3o6dbgozMZbD%2FV4S2my%2FUw%2F7I0Lz9yLwdGcbUseFfLjikAsvSUsE6Il4q0jPBM%2FkbC6FU2xEPxwVFRqnPyLYodGkYYpcVZCiK6HtRbUX9YqtbtMaK4NlFvir9nXhsk0pntpbJf8FkvZEt65r45gW5r%2BuI7kLR3sgw75Of9OsAybqEfrxBHn3Picy7kbmMKGXpp2C%2FxD4fWjlsabn7mm%2BP%2FY5wyNoUWC9eg9kve%2FPp16fFr79vib0L9%2BN5Wssb8ndiPG48L8JxLPrMDnKc4ncS%2BCiEq8WKhuxZfKPDNfLJOoTPLvQERyB4wxEjMMQ34gtGtyB1N8T3HtCB7nh%2FYwbjJ68WGxqRv6Fa5Is64euICWsxnILGMy8JYg2k0FXQeZSDoJdEX9C%2BoPiAYiYELvV9tI3Jy%2FE2AhStSbigjNFAKL1vCMPPW%2BRynXewf94RFshOisGDu8X72lnRj3MNLoRpgFl0ABXpP8I6hPfo0lreM1vUpc4mZ4fGXAiRsP%2F1sepja0%2FgLyhcww0emzvWL9tz1PbmFc2ZpdaQDzMdIoYX3AHivOHBh9yNZqLEHM8wTQkQOdscizI38P8DDdcjw%2FG59bxE8GnNP3GNXYyjz41aPgmxnio9s4icUjOa1VzCDs1aYNQMt6gMxjQZuybFLYUa%2FSVAcrMuSv3622ErlG9ygrKzgz2zxAkj%2BoqX1Kfg1bchTb2f%2BH5JJAHAxytW6%2F4xuBH07iHRubUyyZMwMy6iUHblJzC5IZ6HQ%2B66FIYNpX7KnXJLScgSO7QX8AtmstQm9siGji%2FhWs%2Bu4ZerR2xJQ7gXRBKfxAAC75gDQSf%2BXY%2BrqtMLrwNAa%2BXkumXVO3nB3852Ll1xLsUIuOkfjUCujfqHLCCAufRxNuXfuEXcjnXFLEzVLMwKE%2FDRC%2FYfaUwYobz%2BKNUtmUbT7BfNm4QbHBHW47Qf57hp3md9zbpRMeuLhHHdhQwg7NNPKnikGquIBmUdj7wVldwIA8BlCtDJgk5NsRUJvcXhs%2Fehgv8BtBdQdnb5CAcAOKL0h3qw23pwx43tD%2FB6TXjVp7OW%2BCodontPMxVPWwKhHVj1dVj1rMhy7SpW7VQZhPMhVm3aCquemKbSZFWL34NYW5XE2gXTaKbNjCbWxJXufYpYtRbMbxCLqkjMlVDAZzlR5Y7wGRQGWOwaFlPUOYt2Vtmk3RvrtAfW2QPrbJj2WUvw6411OjWsE0JSjgP1pHONGQeL510Aq8ihTsujyw12X%2FmSV6Ph%2BhhFvCaYPPY18mA5HbDnutgzq6BkVUY47Y2RTSsZWeVCNLCyXliZVaJJjtUyHtanJ1akelpmacX2TPPHTXbOLuBkf%2B1QEpmnep%2FDGlLWjrrtoKrHiLi4UdMV7vOcZTWXBVFlKfCBr6tnRrlZ8yIvlAI6hzVJSx%2Fs7QuE1skmTj7FOcB3x%2FA9PZs6VkfUvXFHdatq4I4dcMfT8663hei%2ByKOh7gJVJSQHOLgqHOhWywybxI3u7UJNZS9hlH26Hhjd9Rid7ZQSX60TbdaJRNtlhqFmXtttG4coaLGNus1RI%2BpXUqOYk5vfVE42YFS3GJVCwMXZLqcvxmKoedaBsVzOWBqmff6ds11GVY6zfo81ZwzOXzuaiCnPUI3ddMxukrqiT%2BNxXv5TMoSyxKmt2gF1roo685Z5LquvPJehxknVGc%2BBEvVCiZzSCTtLTkgjJTp1ou8ikzDVGCrJxHCzkNklv5YXubsY%2BtFCUZwwa1ZMGv5GJN16oGBZt4jhRFSfuroJAn4wLi3k0R2f6Opjdhuy3QL8yKOsRVKX7kSGL%2FF2NBzN6AEfzz%2F6VukNWl%2B0zByOvvVCyxrO5FTk3q%2FKy0w1YXDJ2TdlizE5%2BpastAPrujqq6GZL2mX3RbscR5l07K2xZFUwZhu6piHy7zLpInl6BHtiHjKdB5qABB%2By%2F2LGDoI2oR2jxQHFe8L%2B4MUnU1tc%2Filq459v9%2FmLg7zgh8vTUpo%2BlYI%2FU8F0JgVZ4eSqUPoR4ALGjXPDRJjeO7%2Fh06wJxofuIhef8lORvwG6uMYfIeIR9hEjb8WenNg4fOTmn0tplc9ylXcD046JUpnV3EQROuTUhFfVtlPeDNXFupQZYVpjp9uMppoc4%2Bdnh9jgOrHBcQNakqGZekiwEraM3tKlZuVhwDJJbpE%2BxQEifov8KYrjdwgAUk13gyLBVyq1VySK2b9bJWZ91FYzor7Q4rb%2FxK%2BG9brj9drs5iRij1HAcBSxjyigYd6%2FfxRQdxaRL%2BkCmupJftxGqdNnaThCnf1QCvDEDUwT2N%2Bph3EGyLsq5LUOUXStrxjFVo1fr7OD3JA0Mr4juCW8C2UkS0UjHsLEKdHTz7C2hISKYgl7o2%2B5ZvLWwq897OP8NfZI%2FtKn7usx6BKvFch93QHPU54%2F0VTYs8wKmtcby1M3BZ6SMAkWDyVsDb0b%2Fl4FuKLbxBvzAWcoX%2BGgG5K4S22PoICG3rcNCUucXrek4J7wjqeB5Jnh8TFsHUOYahzDVBG3OvOPxK0yftYhEjbzATRUOD0dRMPFDxEF1yRGLo2CS0dn7VnJNNM7UKJgpSLHaaioo3Datkqh1Xx%2Bsl9lfVMkcGr155fpW2LDr9fw3lI3erTJpMLFwUQfOIMsYbZWDfwn1%2Fi08iKMjo5I9qGFtMakRTVjUU9rC78IOS11t0BdM88cT0nWf5ABvep4OqqJnlqBXvzkoDhfd8TSoZcWpMZVpJUVl5YasSyMjxnSbF2wzO%2B%2FLnTnG9XgZerWRNPm2Y9ZwlZzYuq5r0tBetu1wbDKKdAS8%2B1obSjTMUPcT22%2FZtX96hW7HRVoALt%2F7gm7X0Tiswe0cbTRFUx0LIscZLUlXkFXKwjXFbzqYqbUJPrdnmH5ZFAzkklW7BSArTSBNeRXmxhagfsCdXXMS7ivNpkZ8xzGcdDT7N5ATjWMqoD4Uvrq8JvIfoq24pjOxJop354LX7ZjTGQaUSKLPZ%2FM505dzTV41pVh2i1ymjmLLMZrxRU2s1LDOmWXpUC8FP%2F3EZh3sozaNY839GCK5UXOLgf5bc2tvHmkVNTValnT4barZUm%2Fp9Wyxdnq%2FwtTb0wQ%2FCNNvamis029c6hVnyavZGtdZVPVJHhH2VSjo4xnecaqMp4tHrXuLs5U18L%2Bct2dzk4ns1GkJbquzoZ5zdmQb3VoCddiJM4K82v5sqYXU8W6fhT0c8SpEZLrHq7sGH6d8sus2sJv%2Bb0JSkUdMQ3Tcirb6ZU5TNXoTczhPy7STr2q70j7eoH1VCV1yTGyS2emLt%2F6%2FaamoxxI%2BfWFPU6NXTkJfR9vzVDc1M1RMeuhf2jHrz2MNwaR8p0tjXhv1hjDdTLuU3XXf%2Bkj%2FoZ37ZagdYQC%2BPRpQelrzGiEx2i7Pe8Au8KZKkhNPY0q2EiemfK8e3LMaXF80b6s1MMrtEsOtfACUjoyzJtbc3q%2FPBZMHjRSCzUcAeH3%2BpWfU%2BFPb99Oeb8Kp7ZyR7Qkgy4da%2BmKVE%2BLNG5W8SY3o%2BqtCx%2FgcXCZ%2FSmCFDWyP%2Fdg3v0P%3C%2Fdiagram%3E%3C%2Fmxfile%3E)
