### ISSUE TITLE
spring boot jpa pagination and filter | Feb 26

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#85]
create a spring boot application that shows usage of Pagination and Filter

```java
class Employee{
  Long id;
 String name;
 String designation;
}
```
1. api to add employee in database
2. api to list employee from database without pagination
3. api to list employee with pagination and filter by designation
4. What is JPA pagination and Why it is used?

Reference: https://www.bezkoder.com/spring-boot-pagination-filter-jpa-pageable/

**Comment by Ansu-s** [comment]
[Employee-Pagination Application](https://github.com/Ansu-s/pagination/tree/master)
I have meet all the above given criterias for the task  please check and provide feedback. 
I have created a DTO class that will count the number of employee objects are passed to the response and I have also added some employees for the demonstration. It uses flyway for the data migration.
-  Add a new employee  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/7190f299-b48e-47a4-830b-27bb2e9a6374)

- API to fetch all the employees from the database  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/f1fa2c2f-5b29-445b-aa63-00eac0d7bbdd)

- Sorting the response by our provided field  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/c93cd96a-09e2-4602-92df-81743e8e63c4)

- Pagination implementation with a user defined offset and page size limit  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/b6ed3fa1-0939-46a3-8d26-320700fbf7db)

- Pagination with filter by a specific field including the page features like offset and page size  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/593da6aa-8be4-45da-b3cc-1ef31a4a72d8)

**Comment by rkpatra201** [comment]
Perfect
