### ISSUE TITLE
practice questions | feb 27

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#86]
1. segregate even and odd elements in an array. write junit test.
2. what is singleton pattern, give example.
3. what is dependency injection in spring. write a program and add comments to explain.
4. what is the difference between @Componet, @Service, @Repository annotations.
5. write a program to show how to configure a datasource bean.

**Comment by Ansu-s** [comment]
I have uploaded answers of the above questions in [practice-question](https://github.com/Ansu-s/active-tasks/blob/main/java-tasks/practice-questions.md) file please review it.
