### ISSUE TITLE
media api for bookstore app | 9th March | 10pm

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#89]
```java
public class Media{
   Long id;
   String mediaType, // IMG, VIDEO
   String mediaUrl;
   boolean thumbNail;
   Long sequenceId;
   Long itemId;
}
```

1. Write POST (to create Media), PUT(to update Media by id), GET(get media by id), DELETE(delete media by id) api.
2. Use above Model class for Media.
3. Write Controller and Service Class.
4. Write Entity class & Repository Interface.
5. Write proper flyway script.
6. Validate using postman and attach screenshot.
7. Write Unit Test for controller and service with 100% coverage.

**Comment by Ansu-s** [comment]
I have not added the test cases yet, they will be added after your review of the services and controllers so they will have the updated version.
- Add Media  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/9b69a224-a460-4833-8a1e-34df19fa07d3)
- Get All Media  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/7e710cf4-a8c9-4fbe-9601-98730935dd9f)
- Get Media by id  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/5ae8792d-a85f-425d-8c2d-66dbc154369f)
- Put Media by id  
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/f3fd4ef1-b880-40f1-b451-3a57e22fb215)
- Delete Media by id 
![image](https://github.com/learning-project-01/bookstore-app/assets/130679461/dc5b5c5a-70dc-4b3e-9d04-c623bcad9da6)

**Comment by Subhransupanda2000** [comment]
![Screenshot (640)](https://github.com/learning-project-01/bookstore-app/assets/123824203/c2f6f0a3-5100-4281-80e5-9e1090264ed9)
![Screenshot (641)](https://github.com/learning-project-01/bookstore-app/assets/123824203/bdc0b0ee-fe15-4ed6-ba1e-bf63f358cd8b)
![Screenshot (642)](https://github.com/learning-project-01/bookstore-app/assets/123824203/ec60a1ac-42d2-4e09-b28e-0503b8795623)
![Screenshot (643)](https://github.com/learning-project-01/bookstore-app/assets/123824203/edca5ca4-db9e-4918-a53b-b98e89593ae3)
