### ISSUE TITLE
dsa array problems | 21st March 12am

### ISSUE THREAD

**Issue by Ansu-s** [learning-project-01/bookstore-app#98]
- Cover all the dsa problems form below link  
https://youtube.com/playlist?list=PLgUwDviBIf0rENwdL0nEH0uGom9no0nyB&si=lgB-CleQnAzxdDBu
- covering 4 videos per day will suffice the task requirement
- Add junit tests for each program
- Update 4 questions each day is must

**Comment by Ansu-s** [comment]
- DSA problems with junit tests are added [here](https://github.com/Ansu-s/active-tasks/tree/main/dsa-examples/src/main/java)

**Comment by Subhransupanda2000** [comment]
https://github.com/Subhransupanda2000/dsa-2024/pulls
